### ISSUE TITLE
Repeater translation error

### ISSUE THREAD

**Issue by daviskregers** [rainlab/pages-plugin#211]
Hello,

I updated both rainlab-translate and rainlab-pages plugins as well as ran the "composer update" and updated all the dependencies. It seems to be throwing an error once I try to switch languages for the repeater:

`"Call to undefined method October\Rain\Halcyon\Builder::forceFill()" on line 776 of /Users/daviskregers/Repositories/ins/vendor/october/rain/src/Halcyon/Builder.php`

In the layout the repeater code is as follows:

```
{repeater name="header_slider" tab="Slider" prompt="Add more items"}
	{text tab="Content" name="title"    label="Slider title"  }{/text}
	{richeditor tab="Content" name="content"  label="Slider content"}{/richeditor}
	{text tab="Content" name="link"    label="Slider url"}{/text}
	{mediafinder tab="Content" 	mode="image" 	name="image" label="Slider image"}{/mediafinder}
{/repeater}
```

---

After inspecting the /content/static-pages it seems that the first language file has settings like this:

```
header_slider[1][title] = "x"
header_slider[1][content] = "<p>x</p>"
header_slider[1][link] = "x"
header_slider[1][image] = "/homepage-slider/slideshow-demo01.jpg"
```

and the second language:

```
header_slider[2][title] = "y"
header_slider[2][content] = "<p>y</p>"
header_slider[2][link] = "y"
header_slider[2][image] = "/homepage-slider/slideshow-demo01.jpg"
```

Also, I'm not quite sure if the first element index should be 2 for the second language array, but changing it to 1 or both to 0 didn't seem to be solving the issue.

---

Checked the error logs: 

```
exception 'BadMethodCallException' with message 'Call to undefined method October\Rain\Halcyon\Builder::forceFill()' in /var/www/develop/ins/vendor/october/rain/src/Halcyon/Builder.php:776
Stack trace:
#0 [internal function]: October\Rain\Halcyon\Builder->__call('forceFill', Array)
#1 [internal function]: October\Rain\Halcyon\Builder->forceFill(Array)
#2 /var/www/develop/ins/vendor/october/rain/src/Halcyon/Model.php(1651): call_user_func_array(Array, Array)
#3 /var/www/develop/ins/modules/cms/classes/CmsCompoundObject.php(489): October\Rain\Halcyon\Model->__call('forceFill', Array)
#4 /var/www/develop/ins/modules/backend/widgets/Form.php(315): Cms\Classes\CmsCompoundObject->__call('forceFill', Array)
#5 /var/www/develop/ins/modules/backend/widgets/Form.php(315): RainLab\Pages\Classes\Page->forceFill(Array)
#6 /var/www/develop/ins/plugins/rainlab/translate/formwidgets/MLRepeater.php(126): Backend\Widgets\Form->setFormValues(Array)
#7 [internal function]: RainLab\Translate\FormWidgets\MLRepeater->onSwitchItemLocale()
#8 /var/www/develop/ins/modules/backend/classes/Controller.php(515): call_user_func_array(Array, Array)
#9 /var/www/develop/ins/modules/backend/classes/Controller.php(417): Backend\Classes\Controller->runAjaxHandler('formPagefd49176...')
#10 /var/www/develop/ins/modules/backend/classes/Controller.php(227): Backend\Classes\Controller->execAjaxHandlers()
#11 /var/www/develop/ins/modules/backend/classes/BackendController.php(106): Backend\Classes\Controller->run('index', Array)
#12 [internal function]: Backend\Classes\BackendController->run('rainlab/pages')
#13 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#14 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('run', Array)
#15 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Backend\Classes\BackendController), Object(Illuminate\Routing\Route), 'run')
#16 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#21 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(69): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Backend\Classes\BackendController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'run')
#22 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Backend\Classes...', 'run')
#23 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#24 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#30 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#31 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#32 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#33 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#38 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#41 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#44 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#47 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#50 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#52 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#53 /var/www/develop/ins/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#54 /var/www/develop/ins/index.php(44): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#55 {main}
```

**Comment by daftspunk** [comment]
This should be fixed in Build 380+

Ref: https://github.com/octobercms/october/commit/50d3ffb0353e122667ecd8b0af6073eba475c1c4

**Comment by daftspunk** [comment]
Make sure you have bleeding edge updates enabled to get the development changes early.

http://octobercms.com/docs/setup/configuration#edge-updates
